### ISSUE TITLE
Prefix not working

### ISSUE THREAD

**Issue by ManucrackYT** [Pogy-Bot/Pogy#28]
When I want to use a command using prefix (n!), bot doesn't reply.

**Comment by MarkThe** [comment]
me too i have problem at mongoose maybe you have it also

**Comment by MarkThe** [comment]
```2022-11-23 11:24:26 [ERROR] [unhandledRejection] Query was already executed: guild.findOne({ guildId```

**Comment by ManucrackYT** [comment]
That's your error?
Mine I don't have when I try to use prefix, just doesn't reply and in console doesn't send error or something

**Comment by ManucrackYT** [comment]
im using a host but when i use prefix console doesn't sends error or something similar...

**Comment by MayiVT** [comment]
> im using a host but when i use prefix console doesn't sends error or something similar...

Did you checked these on in [Discord developer portal](https://discord.dev/)?
![image](https://user-images.githubusercontent.com/78113457/208497221-e41fd253-b706-4169-80ac-95624ba2f0db.png)

**Comment by ManucrackYT** [comment]
I didn't enable that, thanks a lot!
