### ISSUE TITLE
Lots of bugs

### ISSUE THREAD

**Issue by machoedits** [Pogy-Bot/Pogy#5]
The p!userinfo, p!serverinfo, p!servers and other commands wont work! i tried to set logs in the dashboard and when i delete something in the server it wont show anything not even who joins and leaves

**Comment by peterhanania** [comment]
fixed in https://github.com/Pogy-Bot/Pogy/commit/9dfca80a74fee2289ad17f201e511c3a27d1da4c

I recommend you delete your old src folder and update.
