### ISSUE TITLE
Embed Message 

### ISSUE THREAD

**Issue by Maccroe** [Pogy-Bot/Pogy#8]
Embed message not working in command also and from dashboard also embed not sended.
![IMG_20220819_105410](https://user-images.githubusercontent.com/90520174/185548972-dd7b0580-12b2-4544-9f6c-8965c67fb504.jpg)

**Comment by peterhanania** [comment]
fixed in https://github.com/Pogy-Bot/Pogy/commit/9dfca80a74fee2289ad17f201e511c3a27d1da4c

I recommend you delete your old src folder and update.
